name: Version Check
author: Federico Grandi
description: An action that allows you to check whether your npm package version has been updated

inputs:
  diff-search:
    description: Whether to search the bump commit using diffs (recommended ONLY if not using standard 'npm version' commits)
    required: false
  file-name:
    description: A custom path to the package.json file
    required: false
  file-url:
    description: A URL to use to fetch the package file, instead of loading the local file
    required: false
  assume-same-version:
    description: Whether to use the version fetched from the package file as the old one or the new one (instead of looking at the diffs)
    required: false
  token:
    description: A GitHub token to use when running on private repos
    required: false

outputs:
  changed:
    description: Whether the version has changed in the examined commits
  type:
    description: The type of version change, if detectable (e.g. 'patch')
  version:
    description: The detected version number
  commit:
    description: The SHA of the commit where the version change has been detected

runs:
  using: node12
  main: "lib/index.js"

branding:
  icon: package
  color: green
